name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Container Registry
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > sa_key.json
          gcloud auth activate-service-account --key-file=sa_key.json

      - name: Build and push Docker image to Google Container Registry (GCR)
        run: |
          echo "Building Docker image..."
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dash-app:latest .
          echo "Pushing Docker image to GCR..."
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dash-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dash-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/dash-app:latest --platform managed --region us-central1 --allow-unauthenticated
